FROM node:22

WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install
COPY . .
COPY scripts/wait-for-it.sh /usr/local/bin/wait-for-it
RUN chmod +x /usr/local/bin/wait-for-it

CMD ["wait-for-it", "-h", "postgresql", "-p", "5432", "-t", "10"]
RUN npm run build

EXPOSE 3000
CMD ["node", "dist/main"]
