name: Build and run tests

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: 'npm'
      - run: npm i
      - run: npm run build --if-present
      - run: npm run test
      - run: npm run test:cov
      - name: Coverage
        uses: ArtiomTr/jest-coverage-report-action@v2
